language: ruby
rvm:
  - 2.6
  - 2.5
  - 2.4
  - 2.3
  - 2.2
  - 2.1
  - 2.0.0
  - jruby-18mode # JRuby in 1.8 mode
  - jruby-19mode # JRuby in 1.9 mode
  - ruby-head
  - jruby-head
matrix:
  allow_failures:
    - rvm: jruby-18mode
    - rvm: jruby-19mode
    - rvm: ruby-head
    - rvm: jruby-head
before_install:
  - gem update bundler
script: ruby check-syntax.rb
notifications:
  irc: "irc.freenode.org#nadoka_jp"
